### ISSUE TITLE
Security Vulnerability in lazy-cache@2.0.2 - set-getter@0.1.0

### ISSUE THREAD

**Issue by BiggRonn** [jonschlinkert/lazy-cache#12]
set-getter is vulnerable for versions < 0.1.1

**Comment by doowb** [comment]
Updating to `set-getter@0.1.1` isn't necessary for this package since it specifies `^0.1.0` and npm will resolve to `0.1.1` because it falls within the semver range.

If you're having issues, check out [this guide](https://gist.github.com/jonschlinkert/9a62534c4f8bc76aee6058caa3f05fd6) on steps you can take to ensure your package dependency tools install the latest patch.

When there are other changes to this package, we usually update the dependency version at that time. But until then, it's usually not necessary.
