### ISSUE TITLE
Security vulnerability in lazy-cache@2.0.2

### ISSUE THREAD

**Issue by OronNadiv** [jonschlinkert/lazy-cache#9]
lazy-cache@2.0.2 -> set-getter@0.1.0 -> to-object-path@0.3.0 -> kind-of@3.2.2
kind-of@3.2.2 has [a security vulnerability](https://nvd.nist.gov/vuln/detail/CVE-2019-20149).
Any plan to update the dependencies to address this issue?  I'll be happy to create a PR if you need help.

Thank you!

**Comment by doowb** [comment]
Updating to `set-getter@0.1.1` isn't necessary for this package since it specifies `^0.1.0` and npm will resolve to `0.1.1` because it falls within the semver range.

If you're having issues, check out [this guide](https://gist.github.com/jonschlinkert/9a62534c4f8bc76aee6058caa3f05fd6) on steps you can take to ensure your package dependency tools install the latest patch.

When there are other changes to this package, we usually update the dependency version at that time. But until then, it's usually not necessary.
